ci: update

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,23 +1,23 @@
-#!/bin/bash
+# #!/bin/bash
 
-echo "Running lint check..."
-# ./gradlew detekt
+# echo "Running lint check..."
+# # ./gradlew detekt
 
-if [ $? -ne 0 ]; then
-    echo "Detekt failed, please fix the issues before committing."
-    exit 1
-fi
+# if [ $? -ne 0 ]; then
+#     echo "Detekt failed, please fix the issues before committing."
+#     exit 1
+# fi
 
-# check branch name
-LC_ALL=C
-local_branch="$(git rev-parse --abbrev-ref HEAD)"
-valid_branch_regex="^(main|feat|fix|hotfix|refactor|release|docs|chore|test)\/[a-z0-9._-]+$"
-message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."
+# # check branch name
+# LC_ALL=C
+# local_branch="$(git rev-parse --abbrev-ref HEAD)"
+# valid_branch_regex="^(main|feat|fix|hotfix|refactor|release|docs|chore|test)\/[a-z0-9._-]+$"
+# message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."
 
-if [[ ! $local_branch =~ $valid_branch_regex ]]
-then
-    echo "$message"
-    exit 1
-fi
+# if [[ ! $local_branch =~ $valid_branch_regex ]]
+# then
+#     echo "$message"
+#     exit 1
+# fi
 
-exit 0
+# exit 0
